### PR TITLE
Tmodel train v3 rebased

### PR DESCRIPTION
**Pull request by robgjansen**
This is the code that we have been using to count traffic models for the past ~6 months. It's been stable. It cleanly rebased to the privcount branch. Is there any reason we shouldn't merge this, so new PrivCount deployments could make use of the code?

(After merging, we can delete the tmodel-train-v3-rebased branch to keep things tidy.)

### CODE REVIEW

**Comment by robgjansen** [comment]
Should this be merged into 'privcount-master' or 'privcount'?

**Comment by teor2345** [comment]
I don't mind, but I suggest privcount-master, because otherwise the master branch will be missing this feature. (Or you'll be trying to do a backport, which is a nightmare.)

**Comment by teor2345** [comment]
Hmm, actually, privcount is the default branch, so you should merge to that branch, then merge privcount to privcount-master.

**Comment by robgjansen** [comment]
Originally I assumed that privcount-master was the equivalent of master (but we wanted to avoid using master here since the Tor master branch is its own thing, so we used privcount-master instead). But then I saw that the default branch was set to privcount. So then I was confused.

If privcount is meant to be the stable branch, then I could change the default to privcount-master, merge the tmodel code to privcount-master, and leave privcount as is. Or else I could do what you suggest and merge to privcount, and then merge that to privcount-master.

Is there some other important difference between privcount and privcount-master?

**Comment by robgjansen** [comment]
> If privcount is meant to be the stable branch, then I could change the default to privcount-master, merge the tmodel code to privcount-master, and leave privcount as is.

I favor the above option since the default branch for privcount/privcount is master, and I think the privcount branch is stable. That way, the privcount branch will be stable and not include the traffic model code in both privcount/privcount and privcount/tor, and the master and privcount-master branches will include the traffic model.

Unless, am I misunderstanding the branch names here?

**Comment by teor2345** [comment]
> On 25 Aug 2018, at 00:41, Rob Jansen <notifications@github.com> wrote:
> 
> Originally I assumed that privcount-master was the equivalent of master (but we wanted to avoid using master here since the Tor master branch is its own thing, so we used privcount-master instead). But then I saw that the default branch was set to privcount. So then I was confused.
> 
> If privcount is meant to be the stable branch, then I could change the default to privcount-master, merge the tmodel code to privcount-master, and leave privcount as is. Or else I could do what you suggest and merge to privcount, and then merge that to privcount-master.

I think setting the default branch to privcount-master is a good idea.

Then you can merge the new code to privcount-master.

> Is there some other important difference between privcount and privcount-master?

No, there is not.

**Comment by robgjansen** [comment]
Merged this code into privcount-master using pr #13.

**Pull request closed without merging**
